---

- name: Verify ACM Hub cluster connection
  shell: |-
    oc cluster-info
    oc get managedclusters -A
- name: Create manifests for Namespace and Managed Cluster CR
  kubernetes.core.k8s:
    state: present
    template:
      - path: 'managedcluster.yml'

- name: Pause 20s
  wait_for:
    timeout: 20

- name: Create temporary SPOKE directory
  ansible.builtin.tempfile:
    state: directory
    suffix: spoke
  register: tempdir

- name: Generate the Import Blob
  shell: |-
    oc get secret {{ AKS_NAME }}-import -n {{ AKS_NAME }} -ojsonpath='{.data.crds\.yaml}' | base64 --decode > {{ tempdir.path }}/01_import.yaml
    oc get secret {{ AKS_NAME }}-import -n {{ AKS_NAME }} -ojsonpath='{.data.import\.yaml}' | base64 --decode > {{ tempdir.path }}/04_import.yaml
- name: Switch to Managed Cluster and Apply Import Blob
  shell: |-
    IMPORT_BLOB=$(cat {{ tempdir.path }}/{{ item }} | base64 -w 0)
    az aks command invoke --resource-group {{ AKS_MRG }} \
      --name {{ AKS_NAME }} \
      --subscription {{ AKS_SUB }} \
      --command "echo $IMPORT_BLOB | base64 --decode | kubectl apply -f -"
  with_items:
    - 01_import.yaml
    - 04_import.yaml

- name: Verify Hub and Spoke components
  shell: |
    oc get managedcluster {{ AKS_NAME }} -n {{ AKS_NAME }} -o yaml
    az aks command invoke \
      --resource-group {{ AKS_MRG }} \
      --name {{ AKS_NAME }} \
      --subscription {{ AKS_SUB }} \
      --command "kubectl get ns; kubectl get pods -n open-cluster-management-agent"
  register: hubspoke_out
