apiVersion: v1
kind: Namespace
metadata:
  name: openshift-adp
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-adp-988md
  namespace: openshift-adp
spec:
  targetNamespaces:
  - openshift-adp
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/oadp-operator.openshift-adp: ""
  name: oadp-operator
  namespace: openshift-adp
spec:
  channel: beta
  installPlanApproval: Automatic
  name: oadp-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: oadp-operator.v0.4.2