apiVersion: v1
kind: Namespace
metadata:
  name: {{ AKS_NAME }}
spec: {}
---
apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  labels:
    cloud: auto-detect
    cluster.open-cluster-management.io/clusterset: default
    name: {{ AKS_NAME }}
    vendor: auto-detect
    managed-application: {{ managed_application }}
  name: {{ AKS_NAME }}
spec:
  hubAcceptsClient: true
  leaseDurationSeconds: 60
---
apiVersion: agent.open-cluster-management.io/v1
kind: KlusterletAddonConfig
metadata:
  name: {{ AKS_NAME }}
  namespace: {{ AKS_NAME }}
spec:
  applicationManager:
    enabled: true
  certPolicyController:
    enabled: true
  clusterLabels:
    cloud: auto-detect
    name: {{ AKS_NAME }}
    vendor: auto-detect
  clusterName: {{ AKS_NAME }}
  clusterNamespace: {{ AKS_NAME }}
  iamPolicyController:
    enabled: true
  policyController:
    enabled: true
  proxyConfig: {}
  searchCollector:
    enabled: true
